<Project Sdk="Microsoft.NET.Sdk">

  <Sdk Name="Aspire.AppHost.Sdk" Version="9.5.0" />

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>04a9f772-a831-47ac-af80-2bcccf56f9ca</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" Version="13.0.2" />
    <PackageReference Include="Aspire.Hosting.MongoDB" Version="13.0.2" />
    <PackageReference Include="Aspire.Hosting.RabbitMQ" Version="13.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Hospital.Api.Host\Hospital.Api.Host.csproj" />
    <ProjectReference Include="..\Hospital.Generator.RabbitMq.Host\Hospital.Generator.RabbitMq.Host.csproj" />
  </ItemGroup>

</Project>
