name: .Net Tests

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: 
    - main
  push:
    branches: [lab1, lab2, lab3, lab4, main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: dotnet restore
        run: dotnet restore ./Hospital/Hospital.sln

      - name: Build solution
        run: dotnet build ./Hospital/Hospital.sln --no-restore

      - name: Run tests
        run: dotnet test ./Hospital/Hospital.Tests/Hospital.Tests.csproj --no-build --verbosity detailed